name: Flutterando
port: 3031
db: database.json
statics: pubic/

# storage:
#   name: "storage"

# auth:
#   key: dajdi3cdj8jw40jv89cj4uybfg9wh9vcnvb
#   exp: 3600
#   scape:
#     - storage
#     - file
